
- name: collect configuration backup for network devices
  ios_command:
    commands:
      - show running-config
  register: collect_config_backup
  when: (ansible_network_os is eq("ios"))
  tags:
    - always
    
- name: copy configuration backup into log files
  template:
    src: templates/backups/network_ios_devices.jinja
    dest: "{% if 'never' is in(ansible_run_tags) %}files/backups/{{inventory_hostname}}/{{inventory_hostname}}.backup{% else %}files/backups/{{inventory_hostname}}/{{inventory_hostname}}.{{'%a' | strftime}}.backup{% endif %}"
  when: (ansible_network_os is eq("ios"))
  delegate_to: localhost
  tags:
    - always
